import type { Metadata } from "next";
import { InfoPageShell, InfoSection } from "../../components/InfoPageShell";
import { buildPageMetadata } from "../../utils/seo";

export const metadata: Metadata = buildPageMetadata({
  title: "Terms & Conditions — Vedzovi",
  description: "The terms that govern your use of Vedzovi.",
  path: "/terms",
});

const CONTACT_EMAIL = "contact@vedzovi.com";

export default function TermsPage() {
  return (
    <InfoPageShell title="Terms & Conditions" subtitle="Last updated: July 2026">
      <InfoSection title="Acceptance">
        <p>
          By accessing or using Vedzovi, you agree to be bound by these Terms &amp;
          Conditions. If you do not agree to these terms, please do not use the
          service.
        </p>
      </InfoSection>

      <InfoSection title="Eligibility">
        <p>
          You must be at least 13 years old to use Vedzovi. By using the service, you
          confirm that you meet this requirement and that you have the legal capacity
          to enter into these terms.
        </p>
      </InfoSection>

      <InfoSection title="Accounts">
        <p>
          You are responsible for maintaining the confidentiality of your account
          credentials and for all activity that occurs under your account. Notify us
          immediately if you suspect unauthorized use of your account.
        </p>
      </InfoSection>

      <InfoSection title="Subscriptions">
        <p>
          Vedzovi offers free and paid subscription plans (such as the PRO plan).
          Paid plans unlock additional usage limits and features. Subscription
          details, pricing, and included features are described on our pricing page
          and may be updated from time to time.
        </p>
      </InfoSection>

      <InfoSection title="Payments">
        <p>
          Payments for paid subscriptions are securely processed through Razorpay.
          By subscribing to a paid plan, you authorize Vedzovi and Razorpay to charge
          the applicable subscription fee to your chosen payment method. Vedzovi does
          not store your card, UPI, or net banking credentials.
        </p>
      </InfoSection>

      <InfoSection title="AI Generated Content">
        <p>
          Vedzovi uses artificial intelligence to analyze uploaded videos and generate
          highlight clips, captions, and related outputs. AI-generated results are
          produced automatically and may not always be accurate, complete, or
          suitable for every purpose. You are responsible for reviewing generated
          content before publishing or distributing it.
        </p>
      </InfoSection>

      <InfoSection title="User Responsibilities">
        <ul className="list-disc list-inside space-y-1">
          <li>You must only upload content you own or have the right to use.</li>
          <li>
            You are responsible for how you use clips generated by Vedzovi, including
            compliance with the policies of any platform you publish to.
          </li>
          <li>You must keep your account information accurate and up to date.</li>
        </ul>
      </InfoSection>

      <InfoSection title="Acceptable Use">
        <p>You agree not to use Vedzovi to:</p>
        <ul className="list-disc list-inside space-y-1 mt-2">
          <li>Upload content that infringes on the intellectual property or rights of others.</li>
          <li>Upload unlawful, defamatory, or harmful content.</li>
          <li>Attempt to disrupt, reverse engineer, or gain unauthorized access to the platform.</li>
          <li>Use the service for any purpose that violates applicable law.</li>
        </ul>
      </InfoSection>

      <InfoSection title="Intellectual Property">
        <p>
          Users retain ownership of the videos and content they upload. By uploading
          content, you grant Vedzovi a limited license to process that content solely
          to provide the highlight generation service to you. The Vedzovi platform,
          branding, and underlying technology remain the property of Vedzovi.
        </p>
      </InfoSection>

      <InfoSection title="Termination">
        <p>
          We may suspend or terminate access to Vedzovi for accounts that violate
          these terms, misuse the service, or engage in fraudulent activity. You may
          stop using Vedzovi and close your account at any time.
        </p>
      </InfoSection>

      <InfoSection title="Disclaimer">
        <p>
          Vedzovi is provided on an &quot;as available&quot; basis, without warranties
          of any kind, express or implied. We do not guarantee that the service will
          be uninterrupted, error-free, or that AI-generated results will meet your
          expectations.
        </p>
      </InfoSection>

      <InfoSection title="Limitation of Liability">
        <p>
          To the extent permitted by law, Vedzovi and its team shall not be liable for
          any indirect, incidental, special, or consequential damages arising from
          your use of, or inability to use, the service.
        </p>
      </InfoSection>

      <InfoSection title="Governing Law">
        <p>
          These Terms &amp; Conditions are governed by the laws of India, without
          regard to conflict of law principles. Any disputes arising from these terms
          shall be subject to the exclusive jurisdiction of the courts of India.
        </p>
      </InfoSection>

      <InfoSection title="Contact">
        <p>
          Questions about these Terms &amp; Conditions can be sent to{" "}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-green-400 hover:text-green-300 transition-colors"
          >
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </InfoSection>
    </InfoPageShell>
  );
}
